// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Root layout에서 locale별 lang을 동적으로 바꾸려면 구조가 더 필요함.
  // 우선 기본값으로 ko를 둠(Next-Intl은 별도로 locale을 주입).
  return (
    <html lang="ko">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
